"""role rating sets

Revision ID: 2eaa9c8261c3
Revises: 1ca566836e35
Create Date: 2026-01-09 02:33:06.840454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaa9c8261c3'
down_revision: Union[str, Sequence[str], None] = '1ca566836e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_set_table', sa.Column('server_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'rating_set_table', 'server_table', ['server_id'], ['id'], ondelete='CASCADE')
    op.add_column('role_set_table', sa.Column('server_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'role_set_table', 'server_table', ['server_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('server_table_rating_set_id_fkey'), 'server_table', type_='foreignkey')
    op.drop_constraint(op.f('server_table_role_set_id_fkey'), 'server_table', type_='foreignkey')
    op.drop_column('server_table', 'rating_set_id')
    op.drop_column('server_table', 'role_set_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_table', sa.Column('role_set_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('server_table', sa.Column('rating_set_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('server_table_role_set_id_fkey'), 'server_table', 'role_set_table', ['role_set_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('server_table_rating_set_id_fkey'), 'server_table', 'rating_set_table', ['rating_set_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'role_set_table', type_='foreignkey')
    op.drop_column('role_set_table', 'server_id')
    op.drop_constraint(None, 'rating_set_table', type_='foreignkey')
    op.drop_column('rating_set_table', 'server_id')
    # ### end Alembic commands ###
