"""initial commit

Revision ID: aa1aa0e0ba40
Revises: 
Create Date: 2025-12-06 03:44:58.981818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1aa0e0ba40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('banner_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permission_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name')
    )
    op.create_table('rating_set_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('min_rating', sa.Integer(), nullable=False),
    sa.Column('max_rating', sa.Integer(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restriction_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_set_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_role_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role_set_id', sa.Uuid(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('icon_id', sa.Uuid(), nullable=True),
    sa.Column('min_in_team', sa.Integer(), nullable=False),
    sa.Column('max_in_team', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_set_id'], ['role_set_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('icon_id', sa.Uuid(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('rating_set_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rating_set_id'], ['rating_set_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('icon_id', sa.Uuid(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('banner_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_set_id', sa.Uuid(), nullable=False),
    sa.Column('rating_set_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rating_set_id'], ['rating_set_table.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_set_id'], ['role_set_table.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['server_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'game_id', name='uq_server_game_pair')
    )
    op.create_table('server_role_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name', name='uq_server_role_name_per_server')
    )
    op.create_table('member_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('server_role_id', sa.Uuid(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_role_id'], ['server_role_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'user_id', name='uq_member_server_user')
    )
    op.create_table('server_role_permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_role_id'], ['server_role_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_role_id', 'permission_id', name='uq_role_permission_pair')
    )
    op.create_table('custom_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['member_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['member_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('use_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['member_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['server_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('member_restriction_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('restriction_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['member_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['member_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restriction_id'], ['restriction_table.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_rating_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('custom_id', sa.Uuid(), nullable=False),
    sa.Column('game_role_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_id'], ['custom_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_role_id'], ['game_role_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id', 'game_role_id', name='uq_custom_gamerole_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_rating_table')
    op.drop_table('member_restriction_table')
    op.drop_table('invite_table')
    op.drop_table('custom_table')
    op.drop_table('server_role_permission')
    op.drop_table('member_table')
    op.drop_table('server_role_table')
    op.drop_table('server_game')
    op.drop_table('server_table')
    op.drop_table('rating_table')
    op.drop_table('game_role_table')
    op.drop_table('role_set_table')
    op.drop_table('restriction_table')
    op.drop_table('rating_set_table')
    op.drop_table('permission_table')
    op.drop_table('game_table')
    # ### end Alembic commands ###
