from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.custom import Custom, CustomCreate


class CustomRepositoryProtocol(Protocol):
    async def get(self, custom_id: UUID, /) -> Custom | None: ...
    async def list_for_member(self, member_id: UUID) -> Sequence[Custom]: ...
    async def create(self, dto: CustomCreate) -> Custom: ...
    async def delete(self, custom_id: UUID, /) -> bool: ...
