from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.game import Game, GameCreate, GameUpdate
from src.core.models.server_game import ServerGame


class GameRepositoryProtocol(Protocol):
    async def get(self, game_id: UUID, /) -> Game | None: ...
    async def get_by_name(self, name: str) -> Game | None: ...
    async def get_all(self) -> Sequence[Game]: ...
    async def list_for_server(self, server_id: UUID) -> Sequence[Game]: ...
    async def create(self, dto: GameCreate) -> Game: ...
    async def update(self, dto: GameUpdate) -> Game: ...
    async def delete(self, game_id: UUID, /) -> bool: ...
    async def add_to_server(self, game_id: UUID, server_id: UUID) -> ServerGame: ...
    async def remove_from_server(self, game_id: UUID, server_id: UUID) -> bool: ...
    async def bulk_add_to_server(self, server_id: UUID, game_ids: list[UUID]) -> list[ServerGame]: ...
    async def bulk_remove_from_server(self, server_id: UUID, game_ids: list[UUID]) -> int: ...
    async def set_server_games(self, server_id: UUID, game_ids: list[UUID]) -> None: ...
