from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.game_role import GameRole, GameRoleCreate, GameRoleUpdate


class GameRoleRepositoryProtocol(Protocol):
    async def get(self, role_id: UUID, /) -> GameRole | None: ...
    async def list_for_set(self, role_set_id: UUID) -> Sequence[GameRole]: ...
    async def create(self, dto: GameRoleCreate) -> GameRole: ...
    async def update(self, dto: GameRoleUpdate) -> GameRole: ...
    async def delete(self, role_id: UUID, /) -> bool: ...
