from typing import Protocol
from uuid import UUID

from src.core.models.game_role_set import (
    GameRoleSet,
    GameRoleSetCreate,
    GameRoleSetDetail,
    GameRoleSetUpdate,
)


class GameRoleSetRepositoryProtocol(Protocol):
    async def get(self, role_set_id: UUID, /) -> GameRoleSet | None: ...
    async def get_by_game_id(self, game_id: UUID) -> GameRoleSet | None: ...
    async def get_detail(self, role_set_id: UUID) -> GameRoleSetDetail | None: ...
    async def create(self, dto: GameRoleSetCreate) -> GameRoleSet: ...
    async def update(self, dto: GameRoleSetUpdate) -> GameRoleSet: ...
    async def delete(self, role_set_id: UUID, /) -> bool: ...
