from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.game_role_set import GameRoleSet, GameRoleSetUpdate


class GameRoleSetRepositoryProtocol(Protocol):
    async def get(self, role_set_id: UUID, /) -> GameRoleSet | None: ...
    async def get_by_server_id(self, server_id: UUID) -> GameRoleSet | None: ...
    async def get_global(self) -> Sequence[GameRoleSet]: ...
    async def copy_global(self, global_role_set: GameRoleSet, server_id: UUID | None = None) -> GameRoleSet: ...
    async def update(self, dto: GameRoleSetUpdate) -> GameRoleSet: ...
