from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.invite import Invite, InviteCreate


class InviteRepositoryProtocol(Protocol):
    async def get(self, invite_id: UUID, /) -> Invite | None: ...
    async def get_by_key(self, key: str) -> Invite | None: ...
    async def list_for_server(self, server_id: UUID) -> Sequence[Invite]: ...
    async def create(self, dto: InviteCreate) -> Invite: ...
    async def decrement_use_limit(self, invite: Invite) -> Invite: ...
    async def delete(self, invite_id: UUID, /) -> bool: ...
