from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.member import Member, MemberCreate, MemberUpdate


class MemberRepositoryProtocol(Protocol):
    async def get(self, member_id: UUID, /) -> Member | None: ...
    async def get_by_user_in_server(self, server_id: UUID, user_id: UUID) -> Member | None: ...
    async def list_active_for_server(self, server_id: UUID, page: int | None = None, nickname_filter: str | None = None, page_size: int = 50) -> Sequence[Member]: ...
    async def create(self, dto: MemberCreate) -> Member: ...
    async def update(self, dto: MemberUpdate) -> Member: ...
    async def set_user_if_none(self, member: Member, user_id: UUID) -> bool: ...
    async def delete(self, member_id: UUID, /) -> bool: ...
