from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.permission import Permission, PermissionCreate


class PermissionRepositoryProtocol(Protocol):
    async def get(self, permission_id: UUID, /) -> Permission | None: ...
    async def get_by_code_bulk(self, code_names: list[str]) -> Sequence[Permission]: ...
    async def list_all(self) -> Sequence[Permission]: ...
    async def list_for_role(self, server_role_id: UUID | None) -> Sequence[Permission]: ...
    async def create(self, dto: PermissionCreate) -> Permission: ...
    async def assign_to_role(self, permission_id: UUID, server_role_id: UUID) -> None: ...
    async def remove_from_role(self, permission_id: UUID, server_role_id: UUID) -> bool: ...
    async def bulk_set_for_role(self, permission_ids: list[UUID], server_role_id: UUID) -> None: ...
