from typing import Protocol
from uuid import UUID

from src.core.models.rating_set import (
    RatingSet,
    RatingSetCreate,
    RatingSetDetail,
    RatingSetUpdate,
)


class RatingSetRepositoryProtocol(Protocol):
    async def get(self, rating_set_id: UUID, /) -> RatingSet | None: ...
    async def get_by_game_id(self, game_id: UUID) -> RatingSet | None: ...
    async def get_detail(self, rating_set_id: UUID) -> RatingSetDetail | None: ...
    async def create(self, dto: RatingSetCreate) -> RatingSet: ...
    async def update(self, dto: RatingSetUpdate) -> RatingSet: ...
    async def delete(self, rating_set_id: UUID, /) -> bool: ...
