from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.rating import Rating, RatingCreate, RatingUpdate


class RatingRepositoryProtocol(Protocol):
    async def get(self, rating_id: UUID, /) -> Rating | None: ...
    async def list_for_set(self, rating_set_id: UUID) -> Sequence[Rating]: ...
    async def create(self, dto: RatingCreate) -> Rating: ...
    async def update(self, dto: RatingUpdate) -> Rating: ...
    async def delete(self, rating_id: UUID, /) -> bool: ...
