from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.rating_set import RatingSet, RatingSetUpdate


class RatingSetRepositoryProtocol(Protocol):
    async def get(self, rating_set_id: UUID, /) -> RatingSet | None: ...
    async def get_by_server_id(self, server_id: UUID) -> RatingSet | None: ...
    async def get_global(self) -> Sequence[RatingSet]: ...
    async def copy_global(self, global_rating_set: RatingSet, server_id: UUID | None = None) -> RatingSet: ...
    async def update(self, dto: RatingSetUpdate) -> RatingSet: ...
