from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.restriction import Restriction, RestrictionCreate


class RestrictionRepositoryProtocol(Protocol):
    async def get(self, code_id: UUID, /) -> Restriction | None: ...
    async def get_by_code_bulk(self, codes: Sequence[str]) -> Sequence[Restriction]: ...
    async def list_all(self) -> Sequence[Restriction]: ...
    async def create(self, dto: RestrictionCreate) -> Restriction: ...
