from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.server_role import ServerRole, ServerRoleCreate, ServerRoleUpdate


class ServerRoleRepositoryProtocol(Protocol):
    async def get(self, role_id: UUID, /) -> ServerRole | None: ...
    async def list_for_server(self, server_id: UUID) -> Sequence[ServerRole]: ...
    async def create(self, dto: ServerRoleCreate) -> ServerRole: ...
    async def update(self, dto: ServerRoleUpdate) -> ServerRole: ...
    async def delete(self, role_id: UUID, /) -> bool: ...
