from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from src.core.models.server import Server, ServerCreate, ServerUpdate


class ServerRepositoryProtocol(Protocol):
    async def get(self, server_id: UUID, /) -> Server | None: ...
    async def list_public(self, page: int | None = None, name_filter: str | None = None, page_size: int = 50) -> Sequence[Server]: ...
    async def list_by_user(self, user_id: UUID, page: int | None = None, name_filter: str | None = None, page_size: int = 50) -> Sequence[Server]: ...
    async def create(self, dto: ServerCreate) -> Server: ...
    async def update(self, dto: ServerUpdate) -> Server: ...
    async def delete(self, server_id: UUID, /) -> bool: ...
